### ISSUE TITLE
SDL_timer

### ISSUE THREAD

**Issue by charles-esterbrook** [Hadeweka/sdl-crystal-bindings-examples#1]
Looks like SDL_timer.h is missing.  SDL_GetPerformanceCounter(), SDL_GetPerformanceFrequency(), etc.

https://github.com/libsdl-org/SDL/blob/SDL2/include/SDL_timer.h

**Comment by Hadeweka** [comment]
There is already a pull request on the main repository to include SDL_timer:

https://github.com/Hadeweka/SDL-Crystal-Bindings/pull/1

Feel free to discuss about the inclusion there.
